shell.executable("/bin/bash")
shell.prefix("source ~/.bashrc; ")

DATASETS = ["Artery_MRAS_CAD", "Artery_PHACTR1_CAD", "Blood_LIPC_HDL", 
            "Liver_CETP_HDL", "Liver_LIPC_HDL", "Liver_SORT1_LDL"]
FORMATS = ["ecav"]

ecaviar = "/proj/milovelab/love/bin/caviar/caviar/eCAVIAR"

rule all:
    input: 
        expand("{data}/{data}.{ext}", data=DATASETS, ext=FORMATS),

rule list_files:
    output:
        tsv = "{data}/{data}.tsv",
        ld = "{data}/{data}.ld"
    shell:
        """
        ls -1 {wildcards.data} | grep eQTLBase.intersect.tsv | sort -V > {output.tsv}
        ls -1 {wildcards.data} | grep intersect.ld | sort -V > {output.ld}
        """

rule twmr:
    input:
        dir = "{data}",
        tsv = "{data}/{data}.tsv"
    output:
        "{data}/{data}.twmr"
    shell:
        "R CMD BATCH --no-save --no-restore '--args {input.dir} {input.tsv} {output}' twmr.R"

rule ecaviar:
    input:
        dir = "{data}",
        tsv = "{data}/{data}.tsv",
        ld = "{data}/{data}.ld"
    output:
        "{data}/{data}.ecav"
    benchmark:
        "bench/{data}_ecav.bench"
    shell:
        "R CMD BATCH --no-save --no-restore '--args {ecaviar} {input.dir} {input.tsv} " 
        "{input.ld} {output}' ecaviar.R"

rule mrlocus:
    input:
        dir = "{data}",
        tsv = "{data}/{data}.tsv",
        ld = "{data}/{data}.ld"
    output:
        "{data}/{data}.mrlocus"
    benchmark:
        "bench/{data}_mrlocus.bench"
    shell:
        "R CMD BATCH --no-save --no-restore '--args {input.dir} {input.tsv} " 
        "{input.ld} {output}' mrlocus.R"

rule ecaviar_mrlocus:
    input:
        dir = "{data}",
        tsv = "{data}/{data}.tsv",
        ld = "{data}/{data}.ld",
        ecav = "{data}/{data}.ecav"
    output:
        "{data}/{data}.ecav-mrlocus"
    benchmark:
        "bench/{data}_ecav-mrlocus.bench"
    shell:
        "R CMD BATCH --no-save --no-restore '--args {input.dir} {input.tsv} " 
        "{input.ld} {input.ecav} {output}' ecaviar-mrlocus.R"

rule collate:
    input:
        tsv = "{data}/{data}.tsv",
	twmr = "{data}/{data}.twmr",
	ptwas = "{data}/{data}.ptwas",
	mrlocus = "{data}/{data}.mrlocus",
	ecav_mrlocus = "{data}/{data}.ecav-mrlocus"
    output:
        "{data}/{data}.final"
    shell:
        "R CMD BATCH --no-save --no-restore '--args {input.tsv} {input.twmr} " 
        "{input.ptwas} {input.mrlocus} {input.ecav_mrlocus} "
        "{output}' collate.R"
