shell.executable("/bin/bash")
shell.prefix("source ~/.bashrc; ")

DATASETS = ["Artery_MRAS_CAD", "Artery_PHACTR1_CAD", 
            "Liver_CEPT_HDL", "Liver_SORT1_LDL"]
FORMATS = ["twmr"]

rule all:
    input: 
        expand("{data}/{data}.{ext}", data=DATASETS, ext=FORMATS),

rule twmr:
    input:
        tsv = "{data}/{data}.tsv"
    output:
        "{data}/{data}.twmr"
    shell:
        "R CMD BATCH --no-save --no-restore '--args {input.tsv} {output}' twmr.R"

rule ecaviar:
    input:
        tsv = "{data}/{data}.tsv",
        ld = "{data}/{data}.ld"
    output:
        "{data}/{data}.ecav"
    shell:
        "R CMD BATCH --no-save --no-restore '--args {input.tsv} " 
        "{input.ld} {output}' ecaviar.R"

rule mrlocus:
    input:
        tsv = "{data}/{data}.tsv",
        ld = "{data}/{data}.ld"
    output:
        mrl = "{data}/{data}.mrlocus",
    shell:
        "R CMD BATCH --no-save --no-restore '--args {input.tsv} " 
        "{input.ld} {output.mrl}' mrlocus.R"

rule ecaviar_mrlocus:
    input:
        tsv = "{data}/{data}.tsv",
        ld = "{data}/{data}.ld",
        ecav = "{data}/{data}.ecav"
    output:
        "{data}/{data}.ecav-mrlocus"
    shell:
        "R CMD BATCH --no-save --no-restore '--args {input.tsv} " 
        "{input.ld} {input.ecav} {output}' ecaviar-mrlocus.R"

rule collate:
    input:
        tsv = "{data}/{data}.tsv",
	twmr = "{data}/{data}.twmr",
	ptwas = "{data}/{data}.ptwas",
	mrlocus = "{data}/{data}.mrlocus",
	ecav_mrlocus = "{data}/{data}.ecav-mrlocus"
    output:
        "{data}/{data}.final"
    shell:
        "R CMD BATCH --no-save --no-restore '--args {input.tsv} {input.twmr} " 
        "{input.ptwas} {input.mrlocus} {input.ecav_mrlocus} "
        "{output}' collate.R"
